name: Terraform Infra CI/CD

on:
  push:
    branches:
      - master

  pull_request:

  workflow_dispatch:
    inputs:
      terraform_destroy:
        description: "Set to true to DESTROY infrastructure"
        required: true
        default: "false"
        type: choice
        options:
          - "false"
          - "true"

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.6

    - name: Terraform Init
      run: terraform init
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      if: github.ref == 'refs/heads/master' && github.event.inputs.terraform_destroy != 'true'
      run: terraform apply -auto-approve

    - name: Terraform Destroy
      if: github.event.inputs.terraform_destroy == 'true'
      run: terraform destroy -auto-approve
